In [3]:
import tensorflow as tf
print(tf.__version__)

2024-05-26 17:25:50.541379: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-26 17:25:50.541841: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-26 17:25:50.544034: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-26 17:25:50.572244: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-26 17:25:51.117637: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF

2.16.1


In [4]:
# Random tensor with uniform distribution
random_tensor_uniform = tf.random.uniform(shape=(3, 2))
random_tensor_uniform

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.8409265 , 0.0396893 ],
       [0.8316064 , 0.0440464 ],
       [0.14054763, 0.608111  ]], dtype=float32)>

In [5]:
# Random tensor with Normal distribution
random_tensor_normal = tf.random.normal(shape=(3, 4))
random_tensor_normal

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-1.0397576 , -0.22494577, -0.8776301 ,  1.2912304 ],
       [-1.4529645 ,  2.740515  , -1.518002  ,  0.14380535],
       [ 0.22875395,  0.78047276,  0.800165  ,  0.97344625]],
      dtype=float32)>

In [6]:
# Random integer tensor
random_tensor_int = tf.random.uniform(shape=(3, 3),minval=1, maxval=10, dtype=tf.int32)
random_tensor_int

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[8, 2, 5],
       [1, 2, 4],
       [7, 5, 9]], dtype=int32)>

In [7]:
# Get standard number output with seed
random_number_int_seed_1 = tf.random.set_seed(12)
random_number_int_seed_1 = tf.random.normal(shape=(3, 3))
random_number_int_seed_2 = tf.random.set_seed(12)
random_number_int_seed_2 = tf.random.normal(shape=(3, 3))
random_number_int_seed_1, random_number_int_seed_2, random_number_int_seed_1 == random_number_int_seed_2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 1.0524982 , -0.60981613,  0.12243897],
        [-1.1777247 , -1.4654896 , -0.53334624],
        [-0.75230265, -0.43710864,  0.9169955 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 1.0524982 , -0.60981613,  0.12243897],
        [-1.1777247 , -1.4654896 , -0.53334624],
        [-0.75230265, -0.43710864,  0.9169955 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [8]:
# setting seed for all distributions
tf.random.set_seed(21)

random_tensor_uniform = tf.random.uniform(shape=(3, 3))
random_tensor_normal = tf.random.normal(shape=(3, 3))
random_tensor_int = tf.random.uniform(shape=(3, 3), minval=1, maxval=10, dtype=tf.int32)
random_tensor_uniform, random_tensor_normal, random_tensor_int

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.02487183, 0.86122084, 0.2314794 ],
        [0.4261533 , 0.07033372, 0.58401775],
        [0.7013489 , 0.754992  , 0.3136698 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-1.1018509 ,  0.23039043,  0.75962853],
        [ 0.60776925, -0.2111087 ,  1.9017993 ],
        [ 0.13315514, -0.5404107 ,  0.7706618 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[8, 9, 6],
        [1, 3, 7],
        [7, 5, 1]], dtype=int32)>)

In [13]:
import tensorflow as tf

# Create a random generator with the Philox algorithm
philox_generator = tf.random.Generator.from_seed(42, alg='philox')

# Create random tensors using the Philox generator
random_tensor_uniform_philox = philox_generator.uniform(shape=(3, 3))
random_tensor_normal_philox = philox_generator.normal(shape=(3, 3))
random_tensor_int_philox = philox_generator.uniform(shape=(3, 3), minval=0, maxval=10, dtype=tf.int32)

print("Philox - Uniform Distribution:\n", random_tensor_uniform_philox)
print("Philox - Normal Distribution:\n", random_tensor_normal_philox)
print("Philox - Integer Tensor:\n", random_tensor_int_philox)


Philox - Uniform Distribution:
 tf.Tensor(
[[0.7493447  0.73561966 0.45230794]
 [0.49039817 0.1889317  0.52027524]
 [0.8736881  0.46921718 0.63932586]], shape=(3, 3), dtype=float32)
Philox - Normal Distribution:
 tf.Tensor(
[[ 0.35215586  1.0294334   1.127859  ]
 [-0.8251682  -1.0670931  -0.6990595 ]
 [-0.6695724  -1.0871812   0.45619673]], shape=(3, 3), dtype=float32)
Philox - Integer Tensor:
 tf.Tensor(
[[9 9 9]
 [7 2 1]
 [4 5 8]], shape=(3, 3), dtype=int32)


In [16]:
import tensorflow as tf

# Create a random generator with the Threefry algorithm
threefry_generator = tf.random.Generator.from_seed(42, alg='threefry')

# Create random tensors using the Threefry generator
random_tensor_uniform_threefry = threefry_generator.uniform(shape=(3, 3))
random_tensor_normal_threefry = threefry_generator.normal(shape=(3, 3))
random_tensor_int_threefry = threefry_generator.uniform(shape=(3, 3), minval=0, maxval=10, dtype=tf.int32)

print("Threefry - Uniform Distribution:\n", random_tensor_uniform_threefry)
print("Threefry - Normal Distribution:\n", random_tensor_normal_threefry)
print("Threefry - Integer Tensor:\n", random_tensor_int_threefry)


2024-05-26 17:29:21.487029: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: UNIMPLEMENTED: Non-XLA devices don't support the ThreeFry algorithm.


UnimplementedError: {{function_node __wrapped__RngReadAndSkip_device_/job:localhost/replica:0/task:0/device:CPU:0}} Non-XLA devices don't support the ThreeFry algorithm. [Op:RngReadAndSkip] name: 

In [18]:
# Ensuring CPU usage
import tensorflow as tf
import os

# Set environment variable to use CPU only
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

# Create a random generator with the Philox algorithm
philox_generator = tf.random.Generator.from_seed(42, alg='philox')

# Create random tensors using the Philox generator
random_tensor_uniform_philox = philox_generator.uniform(shape=(3, 3))
random_tensor_normal_philox = philox_generator.normal(shape=(3, 3))
random_tensor_int_philox = philox_generator.uniform(shape=(3, 3), minval=0, maxval=10, dtype=tf.int32)

print("Philox - Uniform Distribution (CPU):\n", random_tensor_uniform_philox)
print("Philox - Normal Distribution (CPU):\n", random_tensor_normal_philox)
print("Philox - Integer Tensor (CPU):\n", random_tensor_int_philox)


Philox - Uniform Distribution (CPU):
 tf.Tensor(
[[0.7493447  0.73561966 0.45230794]
 [0.49039817 0.1889317  0.52027524]
 [0.8736881  0.46921718 0.63932586]], shape=(3, 3), dtype=float32)
Philox - Normal Distribution (CPU):
 tf.Tensor(
[[ 0.35215586  1.0294334   1.127859  ]
 [-0.8251682  -1.0670931  -0.6990595 ]
 [-0.6695724  -1.0871812   0.45619673]], shape=(3, 3), dtype=float32)
Philox - Integer Tensor (CPU):
 tf.Tensor(
[[9 9 9]
 [7 2 1]
 [4 5 8]], shape=(3, 3), dtype=int32)
