In [6]:
import tensorflow as tf
print(tf.__version__)

2.16.1


In [11]:
scalar = tf.constant(10)
scalar.ndim

0

In [15]:
vector = tf.constant([22, 7])
vector.ndim

1

In [17]:
vector1 = tf.constant([1, 1, 2])
vector1.ndim

1

In [19]:
matrix = tf.constant([[22, 7],
                      [7, 22]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22,  7],
       [ 7, 22]], dtype=int32)>

In [21]:
matrix.ndim

2

In [25]:
matrix1 = tf.constant([[1., 1., 2.],
                       [3., 5., 8.],
                       [13., 21., 34.]], dtype=tf.float16)
matrix1

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[ 1.,  1.,  2.],
       [ 3.,  5.,  8.],
       [13., 21., 34.]], dtype=float16)>

In [28]:
matrix1.ndim

2

In [32]:
matrix2 = tf.constant([[[1, 2, 3],
                        [4, 5, 6]],
                        [[7, 8, 9],
                        [10, 11, 12]],
                        [[13, 14, 15],
                        [16, 17, 18]]])
matrix2how to create 10 dimensional array in tensorflow

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [34]:
matrix2.ndim

3

In [39]:
matrix3 = tf.constant([[[[1,1,1],
                        [1,1,1],
                        [1,1,1]]],
                        [[[2,2,2],
                         [2,2,2],
                         [2,2,2]]],
                         [[[3,3,3],
                          [3,3,3],
                          [3,3,3]]],
                          [[[4,4,4],
                           [4,4,4],
                           [4,4,4]]]])
matrix3

<tf.Tensor: shape=(4, 1, 3, 3), dtype=int32, numpy=
array([[[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       [[[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]]],


       [[[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]]],


       [[[4, 4, 4],
         [4, 4, 4],
         [4, 4, 4]]]], dtype=int32)>

In [40]:
matrix3.ndim

4

In [82]:
uniform_dist1 = tf.random.uniform(shape=[3, 3, 3], seed=10)
uniform_dist1

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0.9168321 , 0.94597244, 0.50883746],
        [0.77070785, 0.5255066 , 0.50538373],
        [0.8332244 , 0.27500176, 0.51483107]],

       [[0.20436502, 0.81574833, 0.04511523],
        [0.85190976, 0.00740945, 0.475888  ],
        [0.24257445, 0.5591289 , 0.41338456]],

       [[0.73941064, 0.87943447, 0.48008025],
        [0.35683215, 0.22773504, 0.38509107],
        [0.10586011, 0.03064466, 0.3993051 ]]], dtype=float32)>

In [95]:
uniform_dist2 = tf.random.uniform(shape=[3, 3, 3], minval=2, maxval=7, dtype=tf.int32, seed=22)
uniform_dist3 = tf.random.uniform(shape=[3, 3, 3], minval=2, maxval=7, dtype=tf.int32, seed=22)
uniform_dist2, uniform_dist3, uniform_dist2 == uniform_dist3

(<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
 array([[[5, 4, 4],
         [5, 5, 3],
         [5, 3, 2]],
 
        [[5, 2, 4],
         [2, 4, 4],
         [2, 3, 4]],
 
        [[5, 3, 5],
         [3, 6, 3],
         [5, 2, 4]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
 array([[[4, 3, 6],
         [2, 5, 2],
         [5, 4, 5]],
 
        [[6, 6, 3],
         [6, 3, 6],
         [3, 2, 3]],
 
        [[4, 6, 4],
         [6, 4, 4],
         [2, 5, 2]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3, 3), dtype=bool, numpy=
 array([[[False, False, False],
         [False,  True, False],
         [ True, False, False]],
 
        [[False, False, False],
         [False, False, False],
         [False, False, False]],
 
        [[False, False, False],
         [False, False, False],
         [False, False, False]]])>)