In [3]:
import tensorflow as tf
print(tf.__version__)

2.16.1


In [28]:
# Random tensor with uniform distribution
random_tensor_uniform = tf.random.uniform(shape=(3, 2))
random_tensor_uniform

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.5854399 , 0.28664017],
       [0.5822307 , 0.09381223],
       [0.30379832, 0.45280004]], dtype=float32)>

In [36]:
# Random tensor with Normal distribution
random_tensor_normal = tf.random.normal(shape=(3, 4))
random_tensor_normal

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.0509439 ,  0.20067136, -0.9261601 , -0.28770185],
       [ 0.5016288 , -0.5977102 , -2.1065514 ,  1.4014736 ],
       [ 0.1877814 , -0.41914663,  1.304298  ,  0.64877164]],
      dtype=float32)>

In [68]:
# Random integer tensor
random_tensor_int = tf.random.uniform(shape=(3, 3),minval=1, maxval=10, dtype=tf.int32)
random_tensor_int

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[9, 9, 8],
       [7, 3, 1],
       [2, 1, 5]], dtype=int32)>

In [119]:
# Get standard number output with seed
random_number_int_seed_1 = tf.random.set_seed(12)
random_number_int_seed_1 = tf.random.normal(shape=(3, 3))
random_number_int_seed_2 = tf.random.set_seed(12)
random_number_int_seed_2 = tf.random.normal(shape=(3, 3))
random_number_int_seed_1, random_number_int_seed_2, random_number_int_seed_1 == random_number_int_seed_2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 1.0524982 , -0.60981613,  0.12243897],
        [-1.1777247 , -1.4654896 , -0.53334624],
        [-0.75230265, -0.43710864,  0.9169955 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 1.0524982 , -0.60981613,  0.12243897],
        [-1.1777247 , -1.4654896 , -0.53334624],
        [-0.75230265, -0.43710864,  0.9169955 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [128]:
# setting seed for all distributions
tf.random.set_seed(21)

random_tensor_uniform = tf.random.uniform(shape=(3, 3))
random_tensor_normal = tf.random.normal(shape=(3, 3))
random_tensor_int = tf.random.uniform(shape=(3, 3), minval=1, maxval=10, dtype=tf.int32)
random_tensor_uniform, random_tensor_normal, random_tensor_int

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.02487183, 0.86122084, 0.2314794 ],
        [0.4261533 , 0.07033372, 0.58401775],
        [0.7013489 , 0.754992  , 0.3136698 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-1.1018509 ,  0.23039043,  0.75962853],
        [ 0.60776925, -0.2111087 ,  1.9017993 ],
        [ 0.13315514, -0.5404107 ,  0.7706618 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[8, 9, 6],
        [1, 3, 7],
        [7, 5, 1]], dtype=int32)>)