In [2]:
import tensorflow as tf
print(tf.__version__)

2.16.1


In [14]:
# Creating a scalar
scalar_1 = tf.constant([10])
scalar_1, scalar_1.numpy()[0]

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([10], dtype=int32)>, 10)

In [15]:
scalar_2 = tf.constant(10)
scalar_2, scalar_2.numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=10>, 10)

In [18]:
# Creating scalar with multiple values
scalar_3 = tf.constant([1, 2, 3, 4])
scalar_3, scalar_3.numpy()

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 array([1, 2, 3, 4], dtype=int32))

In [21]:
scalar_3, scalar_3.ndim, scalar_3.shape

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 1,
 TensorShape([4]))

In [26]:
values_1 = scalar_3.numpy()
values_1_tolist = values_1.tolist()
values_1_tolist

[1, 2, 3, 4]

In [16]:
# Creating a vector
vector_1 = tf.constant([10, 7])
vector_1, vector_1.numpy()[1]

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>, 7)

In [17]:
vector_1.ndim, vector_1.shape, vector_1.dtype

(1, TensorShape([2]), tf.int32)