In [2]:
import tensorflow as tf
print(tf.__version__)

2.16.1


In [14]:
# Creating a scalar
scalar_1 = tf.constant([10])
scalar_1, scalar_1.numpy()[0]

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([10], dtype=int32)>, 10)

In [15]:
scalar_2 = tf.constant(10)
scalar_2, scalar_2.numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=10>, 10)

In [18]:
# Creating scalar with multiple values
scalar_3 = tf.constant([1, 2, 3, 4])
scalar_3, scalar_3.numpy()

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 array([1, 2, 3, 4], dtype=int32))

In [21]:
scalar_3, scalar_3.ndim, scalar_3.shape

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 1,
 TensorShape([4]))

In [26]:
values_1 = scalar_3.numpy()
values_1_tolist = values_1.tolist()
values_1_tolist

[1, 2, 3, 4]

In [16]:
# Creating a vector
vector_1 = tf.constant([10, 7])
vector_1, vector_1.numpy()[1]

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>, 7)

In [17]:
vector_1.ndim, vector_1.shape, vector_1.dtype

(1, TensorShape([2]), tf.int32)

In [28]:
# Create matrix with 2 dimensions
matrix_1 = tf.constant([[10, 7],
                        [3, 4]])
matrix_1.ndim, matrix_1.shape

(2, TensorShape([2, 2]))

In [35]:
# Extract the value from matrix
matrix_1[0], matrix_1[:, 0], matrix_1[0, :], matrix_1[1, :], matrix_1[-1, :], matrix_1[:, -1]

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>)

In [36]:
# Create a matrix with 3 dimensions
matrix_2 = tf.constant([[[10, 7],
                         [3, 4],
                         [1, 2]]])
matrix_2

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4],
        [ 1,  2]]], dtype=int32)>

In [41]:
# Extract the value from matrix
matrix_2[0][0][0].numpy()

10

In [42]:
# Get standard details from given tensor.
matrix_2.ndim, matrix_2.shape, matrix_2.dtype, tf.size(matrix_2)

(3,
 TensorShape([1, 3, 2]),
 tf.int32,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [44]:
# Access 7, 4, 2 from matrix_2
matrix_2[..., -1], matrix_2[:, :, -1]

(<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[7, 4, 2]], dtype=int32)>,
 <tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[7, 4, 2]], dtype=int32)>)

In [57]:
# access 10, 2 from matrix_2
matrix_2, matrix_2[0], matrix_2[0, 0], matrix_2[0, 0, 0]

(<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
 array([[[10,  7],
         [ 3,  4],
         [ 1,  2]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 1,  2]], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=10>)

In [66]:
# just 10 and 2
sliced_values = [matrix_2[0, 0, 0].numpy(), matrix_2[0][2][1].numpy()]
sliced_values

[10, 2]