<a href="https://colab.research.google.com/github/pain459/LTF/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we are going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically we are going to cover:
* Introduction to tensors.
* Getting information from tensors.
* Manipulating tensors.
* Tensors and Numpy
* Using @tf.function(a way to speed up your regular Python functions)
* Using GPU's with Tensorflow (or TPU's)
* Extercises to try for yourself.

# Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [2]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# Check the dimension of the vector
vector.ndim

1

In [8]:
# Create a matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
# Check the size of a matrix
matrix.ndim

2

In [12]:
# Create another matrix
another_matrix = tf.constant([[10., 3.],
                              [3., 10.],
                              [22., 7]], dtype=tf.float16) # Specify the datatype with dtype parameter.
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  3.],
       [ 3., 10.],
       [22.,  7.]], dtype=float16)>

In [13]:
# check the size of a matrix
another_matrix.ndim

2

In [16]:
# Lets create a tensor.
tensor = tf.constant([[[1, 2, 3], [4, 5, 6]],
                      [[7, 8, 9],[10, 11, 12]],
                      [[10, 11, 12], [13, 14, 15]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[10, 11, 12],
        [13, 14, 15]]], dtype=int32)>

In [17]:
# check the size of the matrix
tensor.ndim

3

# What we've created so far:
    * Scalar : A single number
    * Vector : A number with direction (eg. Windspeed and directon)
    * Matrix : A two dimensional array of numbers.
    * Tensor : an n-dimensional array of numbers (where n can be of any number - 0 dimensional number is a scalar, 1 dimensional number is a vector)

### Creating tensors with `tf.Variable`


In [19]:
# create same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 10])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [20]:
# Lets try to change one of the varaiable in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [21]:
# lets try to use assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>