<a href="https://colab.research.google.com/github/pain459/LTF/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we are going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically we are going to cover:
* Introduction to tensors.
* Getting information from tensors.
* Manipulating tensors.
* Tensors and Numpy
* Using @tf.function(a way to speed up your regular Python functions)
* Using GPU's with Tensorflow (or TPU's)
* Extercises to try for yourself.

# Introduction to Tensors

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2024-05-25 16:32:19.445210: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-25 16:32:19.445621: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-25 16:32:19.447831: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-25 16:32:19.474805: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-25 16:32:20.029860: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF

2.16.1


In [3]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check the dimension of the vector
vector.ndim

1

In [7]:
# Create a matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
# Check the size of a matrix
matrix.ndim

2

In [9]:
# Create another matrix
another_matrix = tf.constant([[10., 3.],
                              [3., 10.],
                              [22., 7]], dtype=tf.float16) # Specify the datatype with dtype parameter.
another_matrix

2024-05-25 16:32:50.790123: E tensorflow/core/util/util.cc:131] oneDNN supports DT_HALF only on platforms with AVX-512. Falling back to the default Eigen-based implementation if present.


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  3.],
       [ 3., 10.],
       [22.,  7.]], dtype=float16)>

In [10]:
# check the size of a matrix
another_matrix.ndim

2

In [11]:
# Lets create a tensor.
tensor = tf.constant([[[1, 2, 3], [4, 5, 6]],
                      [[7, 8, 9],[10, 11, 12]],
                      [[10, 11, 12], [13, 14, 15]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[10, 11, 12],
        [13, 14, 15]]], dtype=int32)>

In [12]:
# check the size of the matrix
tensor.ndim

3

# What we've created so far:
    * Scalar : A single number
    * Vector : A number with direction (eg. Windspeed and directon)
    * Matrix : A two dimensional array of numbers.
    * Tensor : an n-dimensional array of numbers (where n can be of any number - 0 dimensional number is a scalar, 1 dimensional number is a vector)

### Creating tensors with `tf.Variable`


In [13]:
# create same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 10])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [15]:
# Lets try to change one of the varaiable in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [21]:
# lets try to use assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [22]:
# lets try to change value in unchangeable tensor
unchangeable_tensor[0].assign(100)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating random tensors

##### Random tensors are tensors of some arbitary size contain random numbers



In [27]:
# create 2 random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducability
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)